[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#6366F1"
backgroundColor = "#F0EDFF"
secondaryBackgroundColor = "#EDE9FE"
textColor = "#1E1B4B"
